# Generated by Django 4.2.1 on 2023-06-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='picture',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(blank=True, choices=[('work', 'work'), ('priority', 'priority'), ('entertainment', 'entertainment'), ('others', 'others'), ('games', 'games'), ('education', 'education')], max_length=255, null=True),
        ),
    ]
