# Generated by Django 4.2.1 on 2023-06-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_service_picture_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='login',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
