# Generated by Django 4.2.1 on 2023-06-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_service_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
